baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  Toc: true
  

languages:
  en:
    languageName: English
    title: Tech Memory
    subtitle: Tech Memory
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: 'tech @ memory: ~ $'
        logoHomeLink: /

    menu:
      main:
      - identifier: posts
        name: Posts
        url: /
      - identifier: tools
        name: Tools
        url: /tools
      - identifier: about
        name: About
        url: /about
      - identifier: cheatsheets
        name: Cheatsheets
        url: /cheatsheets
      - identifier: icon-collections
        name: Icon
        url: /icon-collections